apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opni-metricbeat.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opni-metricbeat.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "opni-metricbeat.name" . }}
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat-oss:7.12.1
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.elasticsearch.host }}
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ .Values.elasticsearch.username }}
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
          {{- with .Values.elasticsearch.passwordSecret }}
            secretKeyRef:
              {{- toYaml . | nindent 14 }}
          {{- end }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
      {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: data
          mountPath: /usr/share/metricbeat/data
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        {{- if .Values.elasticsearch.tls.caSecret.name }}
        - name: ca
          mountPath: /opt/certs
          readOnly: true
        {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: config
        configMap:
          defaultMode: 0640
          name: {{ template "opni-metricbeat.name" . }}-daemonset-config
      - name: modules
        configMap:
          defaultMode: 0640
          name: {{ template "opni-metricbeat.name" . }}-daemonset-modules
      {{- if .Values.elasticsearch.tls.caSecret.name }}
      - name: ca
        secret:
          secretName: {{ .Values.elasticsearch.tls.caSecret.name }}
          items:
          - key: {{ required "Must provide secret key if using caSecret" .Values.elasticsearch.tls.caSecret.key }}
            path: ca.crt
      {{- end }}
      - name: data
        hostPath:
          # When metricbeat runs as non-root user, this directory needs to be writable by group (g+w)
          path: /var/lib/{{ template "opni-metricbeat.name" . }}-data
          type: DirectoryOrCreate