---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "opni-metricbeat.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "opni-metricbeat.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "opni-metricbeat.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "opni-metricbeat.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opni-metricbeat.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opni-metricbeat.labels" . | indent 4 }}